# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cardapio', models.DateField()),
                ('prato_principal', models.CharField(max_length=200)),
                ('sobremesa', models.CharField(max_length=200)),
                ('info_nutricionais', models.TextField(max_length=500)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
